# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' calculate identity
#' 
#' @param aln aligned sequences
#' @param len length of aligned sequence
#' @return numeric vector of identical aminoacids between first seq in the aln object and the rest
#' @export 
calc_identity <- function(aln, len) {
    .Call(`_synal_calc_identity`, aln, len)
}

#' map two sequences
#' 
#' @param aln gapped sequence
#' @param seq ungapped sequence
#' @return a position map from seq->aln
#' @export
map_alignment_sequence <- function(aln, seq) {
    .Call(`_synal_map_alignment_sequence`, aln, seq)
}

