# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' map two sequences
#' 
#' @param aln gapped sequence
#' @param seq ungapped sequence
#' @return a position map from seq->aln
#' @export
map_alignment_sequence <- function(aln, seq) {
    .Call(`_synal_map_alignment_sequence`, aln, seq)
}

